#spring.data.mongodb.uri=mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
my:
servers:
- dev.example.com
- another.example.com
envirment: producer
spring:
  profiles:
    active: test
server:
  port: 8080
